<?php
 echo <<< BLOCK
{
    "Dev1":{
      "_UNIQUE_ID":"Dev1",
      "name":"Klimaanlage",
      "properties":{
         "_humidty":{
            "type":{
               "readable":true,
               "writeable":false
            },
            "value-type":"int",
            "unit":"percent"
         },
 		 "_temperature":{
            "type":{
               "readable":true,
               "writeable":true
            },
            "value-type":"int",
            "unit":"°C"
         },
         "_switch":{
            "type":{
               "readable":false,
               "writeable":true
            },
            "value-type":"bool",
            "allowed-values":[
               "on",
               "off"
            ]
         }
      }
   },
   "Dev5":{
      "_UNIQUE_ID":"Dev5",
      "name":"Heizkörperthermostat",
      "properties":{
         "_switching_status":{
            "type":{
               "readable":false,
               "writeable":true
            },
            "value-type":"int",
            "unit":"state"
         }
      }
   },
   "Dev6":{
      "_UNIQUE_ID":"Dev6",
      "name":"Raumbefeuchter",
      "properties":{
         "_humidty":{
            "type":{
               "readable":false,
               "writeable":true
            },
            "value-type":"int",
            "unit":"%"
         }
      }
   },
   "Dev7":{
      "_UNIQUE_ID":"Dev7",
      "name":"Lichtschalter",
      "properties":{
         "_switch":{
            "type":{
               "readable":true,
               "writeable":true
            },
            "value-type":"bool",
            "allowed-values":[
               "on",
               "off"
            ]
         }
      }
   },
   "Dev8":{
      "_UNIQUE_ID":"Dev8",
      "name":"Thermo- / Hygrosensor",
      "properties":{
         "_temperature":{
            "type":{
               "readable":true,
               "writeable":false
            },
            "status":"20",
            "unit":"°C"
         },
         "_humidty":{
            "type":{
               "readable":true,
               "writeable":false
            },
            "status":"63",
            "unit":"%"
         }
      }
   }
}
BLOCK;
?>